// @generated by protobuf-ts 2.7.0 with parameter generate_dependencies,optimize_code_size
// @generated from protobuf file "protobuf/apps/gs/request/device/device_kind.proto" (package "protobuf.apps.gs.request.device", syntax proto3)
// tslint:disable
/**
 * @generated from protobuf enum protobuf.apps.gs.request.device.DeviceKind
 */
export enum DeviceKind {
    /**
     * @generated from protobuf enum value: ALL = 0;
     */
    ALL = 0,
    /**
     * @generated from protobuf enum value: ANDROID = 1;
     */
    ANDROID = 1,
    /**
     * @generated from protobuf enum value: IOS = 2;
     */
    IOS = 2,
    /**
     * @generated from protobuf enum value: MAC = 3;
     */
    MAC = 3,
    /**
     * @generated from protobuf enum value: WINDOWS = 4;
     */
    WINDOWS = 4,
    /**
     * @generated from protobuf enum value: WINDOWSXP = 5;
     */
    WINDOWSXP = 5,
    /**
     * @generated from protobuf enum value: LINUX = 6;
     */
    LINUX = 6
}
