// @generated by protobuf-ts 2.7.0 with parameter generate_dependencies,optimize_code_size
// @generated from protobuf file "protobuf/apps/gs/request/device/export_as_csv.proto" (package "protobuf.apps.gs.request.device", syntax proto3)
// tslint:disable
import { MessageType } from "@protobuf-ts/runtime";
import { DeviceKind } from "./device_kind";
import { BehindDeviceVersionsFilter } from "../../behind_device_versions_filter";
/**
 * @generated from protobuf message protobuf.apps.gs.request.device.ExportAsCsv
 */
export interface ExportAsCsv {
    /**
     * @generated from protobuf field: protobuf.apps.gs.BehindDeviceVersionsFilter versions_filter = 1;
     */
    versionsFilter: BehindDeviceVersionsFilter;
    /**
     * @generated from protobuf field: protobuf.apps.gs.request.device.DeviceKind filter_by = 2;
     */
    filterBy: DeviceKind;
}
// @generated message type with reflection information, may provide speed optimized methods
class ExportAsCsv$Type extends MessageType<ExportAsCsv> {
    constructor() {
        super("protobuf.apps.gs.request.device.ExportAsCsv", [
            { no: 1, name: "versions_filter", kind: "enum", T: () => ["protobuf.apps.gs.BehindDeviceVersionsFilter", BehindDeviceVersionsFilter] },
            { no: 2, name: "filter_by", kind: "enum", T: () => ["protobuf.apps.gs.request.device.DeviceKind", DeviceKind] }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message protobuf.apps.gs.request.device.ExportAsCsv
 */
export const ExportAsCsv = new ExportAsCsv$Type();
