// @generated by protobuf-ts 2.7.0 with parameter generate_dependencies,optimize_code_size
// @generated from protobuf file "protobuf/apps/gs/request/device/index.proto" (package "protobuf.apps.gs.request.device", syntax proto3)
// tslint:disable
import { MessageType } from "@protobuf-ts/runtime";
import { BehindDeviceVersionsFilter } from "../../behind_device_versions_filter";
import { DeviceKind } from "./device_kind";
/**
 * @generated from protobuf message protobuf.apps.gs.request.device.Index
 */
export interface Index {
    /**
     * @generated from protobuf field: uint32 page = 1;
     */
    page: number;
    /**
     * @generated from protobuf field: uint32 per_page = 2;
     */
    perPage: number;
    /**
     * @generated from protobuf field: string search = 3;
     */
    search: string;
    /**
     * @generated from protobuf field: protobuf.apps.gs.request.device.DeviceKind filter_by = 4;
     */
    filterBy: DeviceKind;
    /**
     * @generated from protobuf field: protobuf.apps.gs.BehindDeviceVersionsFilter versions_filter = 5;
     */
    versionsFilter: BehindDeviceVersionsFilter;
}
// @generated message type with reflection information, may provide speed optimized methods
class Index$Type extends MessageType<Index> {
    constructor() {
        super("protobuf.apps.gs.request.device.Index", [
            { no: 1, name: "page", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 2, name: "per_page", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 3, name: "search", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "filter_by", kind: "enum", T: () => ["protobuf.apps.gs.request.device.DeviceKind", DeviceKind] },
            { no: 5, name: "versions_filter", kind: "enum", T: () => ["protobuf.apps.gs.BehindDeviceVersionsFilter", BehindDeviceVersionsFilter] }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message protobuf.apps.gs.request.device.Index
 */
export const Index = new Index$Type();
