// @generated by protobuf-ts 2.7.0 with parameter generate_dependencies,optimize_code_size
// @generated from protobuf file "protobuf/apps/gs/request/device/remove.proto" (package "protobuf.apps.gs.request.device", syntax proto3)
// tslint:disable
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message protobuf.apps.gs.request.device.Remove
 */
export interface Remove {
    /**
     * @generated from protobuf field: repeated uint32 device_ids = 1;
     */
    deviceIds: number[];
}
// @generated message type with reflection information, may provide speed optimized methods
class Remove$Type extends MessageType<Remove> {
    constructor() {
        super("protobuf.apps.gs.request.device.Remove", [
            { no: 1, name: "device_ids", kind: "scalar", repeat: 1 /*RepeatType.PACKED*/, T: 13 /*ScalarType.UINT32*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message protobuf.apps.gs.request.device.Remove
 */
export const Remove = new Remove$Type();
