// @generated by protobuf-ts 2.7.0 with parameter generate_dependencies,optimize_code_size
// @generated from protobuf file "protobuf/apps/gs/response/device/devices.proto" (package "protobuf.apps.gs.response.device", syntax proto3)
// tslint:disable
import { MessageType } from "@protobuf-ts/runtime";
import { Pagination } from "../../../../response/pagination";
import { Device } from "../../device";
/**
 * @generated from protobuf message protobuf.apps.gs.response.device.Devices
 */
export interface Devices {
    /**
     * @generated from protobuf field: repeated protobuf.apps.gs.Device data = 1;
     */
    data: Device[];
    /**
     * @generated from protobuf field: protobuf.response.Pagination meta = 2;
     */
    meta?: Pagination;
}
// @generated message type with reflection information, may provide speed optimized methods
class Devices$Type extends MessageType<Devices> {
    constructor() {
        super("protobuf.apps.gs.response.device.Devices", [
            { no: 1, name: "data", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => Device },
            { no: 2, name: "meta", kind: "message", T: () => Pagination }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message protobuf.apps.gs.response.device.Devices
 */
export const Devices = new Devices$Type();
