// @generated by protobuf-ts 2.7.0 with parameter generate_dependencies,optimize_code_size
// @generated from protobuf file "protobuf/apps/gs/response/device/devices_info_counters.proto" (package "protobuf.apps.gs.response.device", syntax proto3)
// tslint:disable
import { MessageType } from "@protobuf-ts/runtime";
import { BehindDeviceVersionsCounters } from "./behind_device_versions_counters";
import { AppVersions } from "./app_versions";
/**
 * @generated from protobuf message protobuf.apps.gs.response.device.DevicesInfoCounters
 */
export interface DevicesInfoCounters {
    /**
     * @generated from protobuf field: repeated protobuf.apps.gs.response.device.DevicesInfoCounters.ApplicationTypeInfo data = 1;
     */
    data: DevicesInfoCounters_ApplicationTypeInfo[];
}
/**
 * @generated from protobuf message protobuf.apps.gs.response.device.DevicesInfoCounters.ApplicationTypeInfo
 */
export interface DevicesInfoCounters_ApplicationTypeInfo {
    /**
     * @generated from protobuf field: string application_type = 1;
     */
    applicationType: string;
    /**
     * @generated from protobuf field: string display_name = 2;
     */
    displayName: string;
    /**
     * @generated from protobuf field: protobuf.apps.gs.response.device.AppVersions app_versions = 3;
     */
    appVersions?: AppVersions;
    /**
     * @generated from protobuf field: protobuf.apps.gs.response.device.BehindDeviceVersionsCounters behind_device_versions_counter = 4;
     */
    behindDeviceVersionsCounter?: BehindDeviceVersionsCounters;
}
// @generated message type with reflection information, may provide speed optimized methods
class DevicesInfoCounters$Type extends MessageType<DevicesInfoCounters> {
    constructor() {
        super("protobuf.apps.gs.response.device.DevicesInfoCounters", [
            { no: 1, name: "data", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => DevicesInfoCounters_ApplicationTypeInfo }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message protobuf.apps.gs.response.device.DevicesInfoCounters
 */
export const DevicesInfoCounters = new DevicesInfoCounters$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DevicesInfoCounters_ApplicationTypeInfo$Type extends MessageType<DevicesInfoCounters_ApplicationTypeInfo> {
    constructor() {
        super("protobuf.apps.gs.response.device.DevicesInfoCounters.ApplicationTypeInfo", [
            { no: 1, name: "application_type", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "display_name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "app_versions", kind: "message", T: () => AppVersions },
            { no: 4, name: "behind_device_versions_counter", kind: "message", T: () => BehindDeviceVersionsCounters }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message protobuf.apps.gs.response.device.DevicesInfoCounters.ApplicationTypeInfo
 */
export const DevicesInfoCounters_ApplicationTypeInfo = new DevicesInfoCounters_ApplicationTypeInfo$Type();
