// @generated by protobuf-ts 2.7.0 with parameter generate_dependencies,optimize_code_size
// @generated from protobuf file "protobuf/apps/gs/response/device/updated_devices.proto" (package "protobuf.apps.gs.response.device", syntax proto3)
// tslint:disable
import { MessageType } from "@protobuf-ts/runtime";
import { Device } from "../../device";
/**
 * @generated from protobuf message protobuf.apps.gs.response.device.UpdatedDevices
 */
export interface UpdatedDevices {
    /**
     * @generated from protobuf field: protobuf.apps.gs.response.device.UpdatedDevices.Data data = 1;
     */
    data?: UpdatedDevices_Data;
}
/**
 * @generated from protobuf message protobuf.apps.gs.response.device.UpdatedDevices.Data
 */
export interface UpdatedDevices_Data {
    /**
     * @generated from protobuf field: repeated protobuf.apps.gs.Device devices = 1;
     */
    devices: Device[];
    /**
     * @generated from protobuf field: repeated protobuf.apps.gs.response.device.UpdatedDevices.Data.FailedDevice failed_devices = 2;
     */
    failedDevices: UpdatedDevices_Data_FailedDevice[];
}
/**
 * @generated from protobuf message protobuf.apps.gs.response.device.UpdatedDevices.Data.FailedDevice
 */
export interface UpdatedDevices_Data_FailedDevice {
    /**
     * @generated from protobuf field: uint32 id = 1;
     */
    id: number;
    /**
     * @generated from protobuf field: string error = 2;
     */
    error: string;
}
// @generated message type with reflection information, may provide speed optimized methods
class UpdatedDevices$Type extends MessageType<UpdatedDevices> {
    constructor() {
        super("protobuf.apps.gs.response.device.UpdatedDevices", [
            { no: 1, name: "data", kind: "message", T: () => UpdatedDevices_Data }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message protobuf.apps.gs.response.device.UpdatedDevices
 */
export const UpdatedDevices = new UpdatedDevices$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UpdatedDevices_Data$Type extends MessageType<UpdatedDevices_Data> {
    constructor() {
        super("protobuf.apps.gs.response.device.UpdatedDevices.Data", [
            { no: 1, name: "devices", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => Device },
            { no: 2, name: "failed_devices", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => UpdatedDevices_Data_FailedDevice }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message protobuf.apps.gs.response.device.UpdatedDevices.Data
 */
export const UpdatedDevices_Data = new UpdatedDevices_Data$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UpdatedDevices_Data_FailedDevice$Type extends MessageType<UpdatedDevices_Data_FailedDevice> {
    constructor() {
        super("protobuf.apps.gs.response.device.UpdatedDevices.Data.FailedDevice", [
            { no: 1, name: "id", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 2, name: "error", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message protobuf.apps.gs.response.device.UpdatedDevices.Data.FailedDevice
 */
export const UpdatedDevices_Data_FailedDevice = new UpdatedDevices_Data_FailedDevice$Type();
