// @generated by protobuf-ts 2.7.0 with parameter generate_dependencies,optimize_code_size
// @generated from protobuf file "protobuf/apps/gs/group_tabs.proto" (package "protobuf.apps.gs", syntax proto3)
// tslint:disable
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message protobuf.apps.gs.GroupTabs
 */
export interface GroupTabs {
    /**
     * @generated from protobuf field: repeated protobuf.apps.gs.GroupTabs.ManagePagesRules available_manage_pages = 1;
     */
    availableManagePages: GroupTabs_ManagePagesRules[];
    /**
     * @generated from protobuf field: repeated protobuf.apps.gs.GroupTabs.ManageFeaturesRules available_feature_pages = 2;
     */
    availableFeaturePages: GroupTabs_ManageFeaturesRules[];
}
/**
 * @generated from protobuf enum protobuf.apps.gs.GroupTabs.ManagePagesRules
 */
export enum GroupTabs_ManagePagesRules {
    /**
     * @generated from protobuf enum value: USERS = 0;
     */
    USERS = 0,
    /**
     * @generated from protobuf enum value: ROLES = 1;
     */
    ROLES = 1,
    /**
     * @generated from protobuf enum value: SUBGROUPS = 2;
     */
    SUBGROUPS = 2,
    /**
     * @generated from protobuf enum value: EXTERNAL_GROUPS = 3;
     */
    EXTERNAL_GROUPS = 3,
    /**
     * @generated from protobuf enum value: QUICK_MESSAGES = 4;
     */
    QUICK_MESSAGES = 4,
    /**
     * @generated from protobuf enum value: DEVICES = 5;
     */
    DEVICES = 5,
    /**
     * @generated from protobuf enum value: SECURITY_SETTINGS = 6;
     */
    SECURITY_SETTINGS = 6,
    /**
     * @generated from protobuf enum value: PERSONAL_INVITATIONS = 7;
     */
    PERSONAL_INVITATIONS = 7,
    /**
     * @generated from protobuf enum value: ADMINS = 8;
     */
    ADMINS = 8,
    /**
     * @generated from protobuf enum value: GROUP_SETTINGS = 9;
     */
    GROUP_SETTINGS = 9,
    /**
     * @generated from protobuf enum value: ESCALATION_POLICY = 10;
     */
    ESCALATION_POLICY = 10,
    /**
     * @generated from protobuf enum value: SCHEDULES = 11;
     */
    SCHEDULES = 11,
    /**
     * @generated from protobuf enum value: ONCALL_CALL_ROUTING = 12;
     */
    ONCALL_CALL_ROUTING = 12,
    /**
     * @generated from protobuf enum value: FAILED_CSV_RECORDS = 13;
     */
    FAILED_CSV_RECORDS = 13,
    /**
     * @generated from protobuf enum value: STAGED_CSV_MEMBERS = 14;
     */
    STAGED_CSV_MEMBERS = 14,
    /**
     * @generated from protobuf enum value: STAGED_CSV_NON_MEMBERS = 15;
     */
    STAGED_CSV_NON_MEMBERS = 15,
    /**
     * @generated from protobuf enum value: STAGED_CSV_AD_MEMBERS = 16;
     */
    STAGED_CSV_AD_MEMBERS = 16
}
/**
 * @generated from protobuf enum protobuf.apps.gs.GroupTabs.ManageFeaturesRules
 */
export enum GroupTabs_ManageFeaturesRules {
    /**
     * @generated from protobuf enum value: STOR = 0;
     */
    STOR = 0,
    /**
     * @generated from protobuf enum value: DIRECT = 1;
     */
    DIRECT = 1,
    /**
     * @generated from protobuf enum value: CLOUD_API = 2;
     */
    CLOUD_API = 2,
    /**
     * @generated from protobuf enum value: THIRD_PARTY_INTEGRATIONS = 3;
     */
    THIRD_PARTY_INTEGRATIONS = 3,
    /**
     * @generated from protobuf enum value: EMR = 4;
     */
    EMR = 4,
    /**
     * @generated from protobuf enum value: ASSISTED_CALLS = 5;
     */
    ASSISTED_CALLS = 5,
    /**
     * @generated from protobuf enum value: CARE_CHANNELS = 6;
     */
    CARE_CHANNELS = 6,
    /**
     * @generated from protobuf enum value: USER_MANAGEMENT_API = 7;
     */
    USER_MANAGEMENT_API = 7
}
// @generated message type with reflection information, may provide speed optimized methods
class GroupTabs$Type extends MessageType<GroupTabs> {
    constructor() {
        super("protobuf.apps.gs.GroupTabs", [
            { no: 1, name: "available_manage_pages", kind: "enum", repeat: 1 /*RepeatType.PACKED*/, T: () => ["protobuf.apps.gs.GroupTabs.ManagePagesRules", GroupTabs_ManagePagesRules] },
            { no: 2, name: "available_feature_pages", kind: "enum", repeat: 1 /*RepeatType.PACKED*/, T: () => ["protobuf.apps.gs.GroupTabs.ManageFeaturesRules", GroupTabs_ManageFeaturesRules] }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message protobuf.apps.gs.GroupTabs
 */
export const GroupTabs = new GroupTabs$Type();
