// @generated by protobuf-ts 2.7.0 with parameter generate_dependencies,optimize_code_size
// @generated from protobuf file "protobuf/apps/gs/group_settings.proto" (package "protobuf.apps.gs", syntax proto3)
// tslint:disable
import { MessageType } from "@protobuf-ts/runtime";
import { AppCustomizationSettings } from "./app_customization_settings";
import { BrandingSettings } from "./branding_settings";
/**
 * @generated from protobuf message protobuf.apps.gs.GroupSettings
 */
export interface GroupSettings {
    /**
     * @generated from protobuf field: protobuf.apps.gs.BrandingSettings branding_settings = 1;
     */
    brandingSettings?: BrandingSettings;
    /**
     * @generated from protobuf field: protobuf.apps.gs.AppCustomizationSettings app_customization_settings = 2;
     */
    appCustomizationSettings?: AppCustomizationSettings;
}
// @generated message type with reflection information, may provide speed optimized methods
class GroupSettings$Type extends MessageType<GroupSettings> {
    constructor() {
        super("protobuf.apps.gs.GroupSettings", [
            { no: 1, name: "branding_settings", kind: "message", T: () => BrandingSettings },
            { no: 2, name: "app_customization_settings", kind: "message", T: () => AppCustomizationSettings }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message protobuf.apps.gs.GroupSettings
 */
export const GroupSettings = new GroupSettings$Type();
