// @generated by protobuf-ts 2.7.0 with parameter generate_dependencies,optimize_code_size
// @generated from protobuf file "protobuf/apps/gs/oncall_group.proto" (package "protobuf.apps.gs", syntax proto3)
// tslint:disable
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message protobuf.apps.gs.OncallGroup
 */
export interface OncallGroup {
    /**
     * @generated from protobuf field: uint32 id = 1;
     */
    id: number;
    /**
     * @generated from protobuf field: string name = 2;
     */
    name: string;
}
// @generated message type with reflection information, may provide speed optimized methods
class OncallGroup$Type extends MessageType<OncallGroup> {
    constructor() {
        super("protobuf.apps.gs.OncallGroup", [
            { no: 1, name: "id", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 2, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message protobuf.apps.gs.OncallGroup
 */
export const OncallGroup = new OncallGroup$Type();
